/**
 * NOTE: This class is auto generated by the swagger code generator program (unset).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Error;
import org.threeten.bp.OffsetDateTime;
import io.swagger.model.RetrieveLocationRelation;
import io.swagger.model.RetrieveLocationRelationCreate;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-12-22T19:02:40.482+03:00")

@Api(value = "retrieveLocationRelation", description = "the retrieveLocationRelation API")
public interface RetrieveLocationRelationApi {

    @ApiOperation(value = "Creates a 'RetrieveLocationRelation'", nickname = "createRetrieveLocationRelation", notes = "", response = RetrieveLocationRelation.class, tags={ "retrieveLocationRelation", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Created", response = RetrieveLocationRelation.class),
        @ApiResponse(code = 400, message = "Bad Request", response = Error.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = Error.class) })
    @RequestMapping(value = "/retrieveLocationRelation",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<RetrieveLocationRelation> createRetrieveLocationRelation(@ApiParam(value = "The Retrieve Location Relation to be created" ,required=true )  @Valid @RequestBody RetrieveLocationRelationCreate retrieveLocationRelation);


    @ApiOperation(value = "List or find 'RetrieveLocationRelation' objects", nickname = "listRetrieveLocationRelation", notes = "", response = RetrieveLocationRelation.class, responseContainer = "List", tags={ "retrieveLocationRelation", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Ok", response = RetrieveLocationRelation.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Bad Request", response = Error.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = Error.class) })
    @RequestMapping(value = "/retrieveLocationRelation",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<List<RetrieveLocationRelation>> listRetrieveLocationRelation(@ApiParam(value = "Comma separated properties to display in response") @Valid @RequestParam(value = "fields", required = false) String fields,@ApiParam(value = "For filtering: A string. Status of the task (inProgress, terminatedWithErrror, done).") @Valid @RequestParam(value = "status", required = false) String status,@ApiParam(value = "For filtering: Reference to a location") @Valid @RequestParam(value = "locationA", required = false) String locationA,@ApiParam(value = "For filtering: Reference to a location") @Valid @RequestParam(value = "locationB", required = false) String locationB,@ApiParam(value = "For filtering: Calculated distance between location A and location B") @Valid @RequestParam(value = "distance", required = false) String distance,@ApiParam(value = "For filtering: Timestamp of end of task execution") @Valid @RequestParam(value = "time", required = false) OffsetDateTime time,@ApiParam(value = "For filtering: A string. Name of the geo location.") @Valid @RequestParam(value = "intersection.name", required = false) String intersectionName,@ApiParam(value = "For filtering: A string. Type of the geographic location - one of: point, line, graph, ring polygon") @Valid @RequestParam(value = "intersection.type", required = false) String intersectionType);


    @ApiOperation(value = "Retrieves a 'RetrieveLocationRelation' by Id", nickname = "retrieveRetrieveLocationRelation", notes = "", response = RetrieveLocationRelation.class, responseContainer = "List", tags={ "retrieveLocationRelation", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Ok", response = RetrieveLocationRelation.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Bad Request", response = Error.class),
        @ApiResponse(code = 404, message = "Not Found", response = Error.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = Error.class) })
    @RequestMapping(value = "/retrieveLocationRelation/{id}",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    ResponseEntity<List<RetrieveLocationRelation>> retrieveRetrieveLocationRelation(@ApiParam(value = "Identifier of the Retrieve Location Relation",required=true) @PathVariable("id") String id);

}
